### ISSUE TITLE
Add configuration to exclude names

### ISSUE THREAD

**Issue by ValentinTrinque** [Antonboom/errname#7]
Some verification are a bit too strict, and I couldn't find a way to exclude very specific names.

I have a HTTP service with an `ErrorResponse`, and errname complains about it :

```
the type name `ErrorResponse` should conform to the `XxxError` format (errname)
```

I am running errname through golangci-lint.

**Comment by Antonboom** [comment]
@ValentinTrinque, sorry for long answer.

I thought about this option from the very beginning, but decided that it makes no sense, because there is a way to solve this and similar problem by golangci-lint.

`nolint` does not pollute your code, especially when you specify a specific linter, this is a common practice.

I will not close the issue to understand if this is relevant to someone else.

P.S.
I see a next plus in the configuration: you can see all the specific names in the project in one place (although this can be done using a search for `//nolint:errname`).

**Comment by ValentinTrinque** [comment]
Yes, I agree.

Indeed that's the good thing about the configuration file.

But in the end, searching nolint:errname (or more complexe regexp construct) can do the trick. Also, you are less likely to keep configuration that doesn't link to any code anymore.

At least, this issue helps understand the pros and cons of each technique.
